packages:
  - "apps/*"
  - "packages/*"
  - "evals"
allowBuilds:
  esbuild: true
  protobufjs: true
  argon2: true
  sharp: true
  unrs-resolver: true
  msgpackr-extract: true
  bufferutil: true
  bcrypt: true
