/**
 * Stable, machine-readable error codes. Codes are part of the public API
 * contract: never rename or reuse; only add.
 */
export const ErrorCodes = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // AuthN / AuthZ
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_API_KEY: 'INVALID_API_KEY',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  INVALID_WIDGET_TOKEN: 'INVALID_WIDGET_TOKEN',
  ORIGIN_NOT_ALLOWED: 'ORIGIN_NOT_ALLOWED',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',

  // Tenancy
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  MEMBERSHIP_REQUIRED: 'MEMBERSHIP_REQUIRED',

  // Conversations
  CONVERSATION_CLOSED: 'CONVERSATION_CLOSED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // Knowledge
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  URL_NOT_ALLOWED: 'URL_NOT_ALLOWED',
  INGESTION_FAILED: 'INGESTION_FAILED',
  DOCUMENT_VERSION_CONFLICT: 'DOCUMENT_VERSION_CONFLICT',

  // AI
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  AI_BUDGET_EXCEEDED: 'AI_BUDGET_EXCEEDED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',

  // Tools
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_NOT_APPROVED: 'TOOL_NOT_APPROVED',
  TOOL_ARGS_INVALID: 'TOOL_ARGS_INVALID',
  TOOL_UNAUTHORIZED: 'TOOL_UNAUTHORIZED',
  TOOL_CONFIRMATION_REQUIRED: 'TOOL_CONFIRMATION_REQUIRED',
  TOOL_CONFIRMATION_EXPIRED: 'TOOL_CONFIRMATION_EXPIRED',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  TOOL_TIMEOUT: 'TOOL_TIMEOUT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
